# --- Site settings ---
title: pettersson.dev
email: david@pettersson.dev
description: >-
  Enterprise Architecture made practical - ADM, EDGY, TM Forum. Notes and reflections on software engineering and IT architecture.
url: "https://pettersson.dev"
locale: "en"
timezone: "Europe/Stockholm"

github_username: pettersson-dev
minimal_mistakes_skin: "contrast"   # your current skin
search: true

# --- Build settings ---
markdown: kramdown
highlighter: rouge
remote_theme: mmistakes/minimal-mistakes

# Output
permalink: /:categories/:title/
paginate: 10
paginate_path: /page/:num/

# Include folders
include:
  - _pages

# Exclude from build
exclude:
  - README.md
  - node_modules
  - vendor
  - .github
  - package.json
  - package-lock.json

# --- Plugins (GitHub Pages-safe) ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# --- Theme options ---
breadcrumbs: true
lunr:
  search_within_pages: true

# --- SEO ---
seo:
  type: "Person"
  name: "David Pettersson"
  social:
    links:
      - https://www.linkedin.com/in/petterssondavid
      - https://github.com/pettersson-dev

# --- Author profile ---
author:
  name   : "David Pettersson"
  avatar : "/assets/images/B171E59B-7F3B-48E1-BD7E-61471D87E1C2.jpeg"
  bio    : "Enterprise Architect. I help teams turn strategy into execution."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://pettersson.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pettersson-dev"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:david@pettersson.dev"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/petterssondavid"

# --- Footer links ---
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pettersson-dev"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/petterssondavid"

# --- Analytics ---
analytics:
  provider: "custom"   # keep as-is (you can add Plausible/GA later)

# --- Defaults ---
defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "On this page"
      comments: false
      classes: wide
      excerpt_separator: "<!--more-->"
      image: /assets/images/social/default-og.png
      header:
        overlay_filter: 0.5

  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide

# --- Archives ---
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
